auto_commit_after_request: false
auto_commit_after_delete_request: true

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    max_memory: 128M
    min_memory: 32M
    path: '/solr/tagteam-dev'
  auto_commit_after_request: false
  auto_commit_after_delete_request: true

production:
  solr:
    hostname: localhost
    port: 8987
    log_level: WARNING
    max_memory: 128M
    min_memory: 32M
  auto_commit_after_request: false
  auto_commit_after_delete_request: true

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    max_memory: 128M
    min_memory: 32M
    path: '/solr/tagteam-test'
  auto_commit_after_request: false
  auto_commit_after_delete_request: true
